[[tg-au-executiveSummary]]

= Administrative Units - Executive Summary

_Administrative units_ are included in Annex I, which means that they are considered as reference data, i.e. data that constitute the spatial frame for linking to and/or pointing at other information that belong to specific thematic fields such as the environment and socio-economic statistics, alongside many others.

INSPIRE data specification on administrative units has been prepared following the participative principle of a consensus building process. The stakeholders, based on their registration as a Spatial Data Interest Community (SDIC) or a Legally Mandated Organisation (LMO) had the opportunity to bring forward user requirements and reference materials, propose experts for the specification's development, and to participate in reviewing and testing the data specifications. The Thematic Working Group responsible for the specification development was composed of experts from Belgium, Germany, Norway, Poland and Sweden.

The specification process took place according to the methodology elaborated for INSPIRE respecting the requirements and the recommendation of the INSPIRE Generic Conceptual Model, which is one of the elements that ensures a coherent approach and cross-theme consistency with other themes in the Directive.

During the specification development, the Thematic Working Group has considered widely the achievements of the EuroBoundaryMap product, which already achieved considerable results in harmonising administrative unit data held by the National Mapping and Cadastral Agencies of Europe.

According to the definition of the Directive, administrative units are "units of administration dividing areas where Member States have and/or exercise jurisdictional rights for local, regional and national governance, separated by administrative boundaries". Based on the reference materials and the user requirements, the Thematic Working Group has added some other fundamental aspects like the hierarchical structure of administrative units and the relations with statistical units that have already been defined and in use within the EU-administration.footnote:[Statistical units, such as NUTS (Nomenclature of Territorial Statistical Units) regions, are defined in the _Statistical units_ data theme, which is part of INSPIRE Annex III.]

Administrative units in INSPIRE play the role of generic information locators. Their main uses include 

* Searching / filtering other spatial data based on a name or code. 
* Linking / publishing thematic information in a rapid and comparable way. 
* Finding competent authorities e.g. in case of disasters, for environmental protection , etc.

In addition administrative units may provide the frame for a boundary-based analysis of consistency of spatial objects (similar classification, geometrical matching) as required in Art. 8(4) and 10(2) of the Directive.

The administrative units data theme model is divided in two application schemas:

* The core element of the *AdministrativeUnits application schema* is the administrative unit represented by a surface geometry. In accordance with the Directive, each administrative unit carries a unique identifier. Administrative units are further described by their geographical name, the country of location, the national administrative code, and the hierarchical level within the administrative structure of the country. This information is completed, if available, with the life cycle information (when the administrative unit has been inserted or changed in the dataset, and when it has been (if ever) superseded or retired in the spatial data set), the name of the corresponding national level and the residence of the administrative authority.
+
The administrative division of the Members States follows a hierarchical structure where the lowest level units (often communes) are united in higher level units (like provinces, counties, etc) that compose other units at a higher level. It must be ensured that an administrative unit of an upper level is composed of one or more administrative units of a lower level. Lowest level administrative units are further characterised by their geometry and, where available, by the corresponding local administrative unit code. A special spatial object type called condominium has been introduced for describing independent administrative areas that are administered by two or more countries.
+
Administrative units are separated by administrative boundaries that are specified as lines. As mandatory properties they carry a unique identifier, information on the country, the administrative hierarchic level and their own geometry. These are complemented, when available, with the legal and technical status of the boundary and the life cycle information.

* The *MaritimeUnits application schema* models the existing maritime zones. These are stripes or belts of sea defined according international treaties and conventions, where the coastal States execute their jurisdictional rights. Depending on the zone type property, they may concern an area of seabed, ocean floor, subsoil, resources, or even the air space over the sea, for cadastral, administrative, economic, security or safety purposes. These rights are established by the United Nations Convention on the Law of the Sea (UNCLOS). The baseline, the line from which the outer limits of the territorial sea is measured, serves as reference to calculate the breath of territorial sea, while determines the outer limits of other maritime zones by establishing respectively different distances measured from it.
+
In contrast to the AdministrativeUnits model, no hierarchical structure is established between different maritime zones. However, they share common properties with administrative units, like the unique identifier and the country the maritime zone belongs to. All this information is again complemented, if available, with the life cycle information and the geographical name.
+
Following a common modelling approach with administrative units, maritime zones are separated by maritime boundaries that are specified as lines. As mandatory properties they carry a unique identifier, information on the country, and their own geometry. These are complemented, when available, with the legal and technical status of the boundary and the life cycle information.

In the INSPIRE administrative unit data specification, there are no mandatory quality requirements. However it is recommended that Member States provide the data at the source accuracy where possible targeting a minimal positional accuracy of 50 meters. The actual values of data quality sub-elements (completeness - commission and omission; logical consistency - conceptual, domain and topological consistency; positional accuracy – absolute ore external accuracy) should be published as metadata, when they are available. Metadata information have to be complemented with the necessary elements to comply with the Metadata Regulation 1205/2008/EC, the ones identified as needed for the interoperability of the Administrative Units theme and, if possible, those recommended in this specification.

Interoperability is further supported by a common reference system and provisions for visualisation. For the latter, simple rules for default portrayal are given in specifying the fill colour of the administrative units and maritime zones, and the line-width of their borders corresponding to administrative and maritime boundaries, as well as the font and size of the labels. Moreover, the default portrayal elements reflect the hierarchy of the represented spatial objects.

The main value of the INSPIRE Administrative Units theme data models is that they have a simple, yet flexible structure that allows data providers to publish their existing data in the most convenient way. Additionally, this specification has given a firm starting point for the related spatial data themes in Annex III of INSPIRE.

As INSPIRE _Administrative units_ data specification is the result of a detailed analysis of user requirements and strong consideration of existing initiatives that went beyond the strictly environmental scope, it is expected that it will also be a solid element of a multi-purpose European spatial data infrastructure.