= Reference systems, units of measure and grids

== Default reference systems, units of measure and grid

The reference systems, units of measure and geographic grid systems included in this sub-section are the defaults to be used for all INSPIRE data sets, unless theme-specific exceptions and/or additional requirements are defined in the following sub-section.

=== Coordinate reference systems

==== Datum

[REQUIREMENT, id="IR Requirement"]
======
_Annex II, Section 1.2_ +
*Datum for three-dimensional and two-dimensional coordinate reference systems*

For the three-dimensional and two-dimensional coordinate reference systems and the horizontal component of compound coordinate reference systems used for making spatial data sets available, the datum shall be the datum of the European Terrestrial Reference System 1989 (ETRS89) in areas within its geographical scope, or the datum of the International Terrestrial Reference System (ITRS) or other geodetic coordinate reference systems compliant with ITRS in areas that are outside the geographical scope of ETRS89. Compliant with the ITRS means that the system definition is based on the definition of the ITRS and there is a well documented relationship between both systems, according to EN ISO 19111.
======

==== Coordinate reference systems

[REQUIREMENT, id="IR Requirement"]
======
_Annex II, Section 1.3_ +
*Coordinate Reference Systems*

Spatial data sets shall be made available using at least one of the coordinate reference systems specified in sections 1.3.1, 1.3.2 and 1.3.3, unless one of the conditions specified in section 1.3.4 holds.

1.3.1.	Three-dimensional Coordinate Reference Systems::

* Three-dimensional Cartesian coordinates based on a datum specified in 1.2 and using the parameters of the Geodetic Reference System 1980 (GRS80) ellipsoid.
* Three-dimensional geodetic coordinates (latitude, longitude and ellipsoidal height) based on a datum specified in 1.2 and using the parameters of the GRS80 ellipsoid.

1.3.2.	Two-dimensional Coordinate Reference Systems::

* Two-dimensional geodetic coordinates (latitude and longitude) based on a datum specified in 1.2 and using the parameters of the GRS80 ellipsoid.
* Plane coordinates using the ETRS89 Lambert Azimuthal Equal Area coordinate reference system.
* Plane coordinates using the ETRS89 Lambert Conformal Conic coordinate reference system.
* Plane coordinates using the ETRS89 Transverse Mercator coordinate reference system.

1.3.3.	Compound Coordinate Reference Systems::

. For the horizontal component of the compound coordinate reference system, one of the coordinate reference systems specified in section 1.3.2 shall be used.
. For the vertical component, one of the following coordinate reference systems shall be used:
** For the vertical component on land, the European Vertical Reference System (EVRS) shall be used to express gravity-related heights within its geographical scope. Other vertical reference systems related to the Earth gravity field shall be used to express gravity-related heights in areas that are outside the geographical scope of EVRS.
** For the vertical component in the free atmosphere, barometric pressure, converted to height using ISO 2533:1975 International Standard Atmosphere, or other linear or parametric reference systems shall be used. Where other parametric reference systems are used, these shall be described in an accessible reference using EN ISO 19111-2:2012.
** For the vertical component in marine areas where there is an appreciable tidal range (tidal waters), the Lowest Astronomical Tide (LAT) shall be used as the reference surface.
** For the vertical component in marine areas without an appreciable tidal range, in open oceans and effectively in waters that are deeper than 200 meters, the Mean Sea Level (MSL) or a well-defined reference level close to the MSL shall be used as the reference surface.

1.3.4.	Other Coordinate Reference Systems::

Exceptions, where other coordinate reference systems than those listed in 1.3.1, 1.3.2 or 1.3.3 may be used, are:

.	Other coordinate reference systems may be specified for specific spatial data themes in this Annex.
.	For regions outside of continental Europe, Member States may define suitable coordinate reference systems.

+
The geodetic codes and parameters needed to describe these coordinate reference systems and to allow conversion and transformation operations shall be documented and an identifier shall be created, according to EN ISO 19111 and ISO 19127.
======

==== Display

[REQUIREMENT, id="IR Requirement"]
======
_Annex II, Section 1.4_ +
*Coordinate Reference Systems used in the View Network Service*

For the display of spatial data sets with the view network service as specified in Regulation No 976/2009, at least the coordinate reference systems for two-dimensional geodetic coordinates (latitude, longitude) shall be available.
======

==== Identifiers for coordinate reference systems

[REQUIREMENT, id="IR Requirement"]
======
_Annex II, Section 1.4_ +
*Coordinate Reference Systems used in the View Network Service*

. Coordinate reference system parameters and identifiers shall be managed in one or several common registers for coordinate reference systems.
. Only identifiers contained in a common register shall be used for referring to the coordinate reference systems listed in this Section.
======

These Technical Guidelines propose to use the http URIs provided by the Open Geospatial Consortium as coordinate reference system identifiers (see identifiers for the default CRSs below). These are based on and redirect to the definition in the EPSG Geodetic Parameter Registry (http://www.epsg-registry.org/).

[RECOMMENDATION, id="TG Requirement {counter:tgreq-id}"]
======
The identifiers listed in the table below shall be used for referring to the coordinate reference systems used in a data set.
======

[NOTE]
====
CRS identifiers may be used e.g. in: +

* data encoding,
* data set and service metadata, and
* requests to INSPIRE network services.
====

.http URIs for the default coordinate reference systems
[cols="40%,20%,40%"]
|===

| *Coordinate reference system* | *Short name* | *http URI identifier*

|3D Cartesian in ETRS89
|ETRS89-XYZ
|http://www.opengis.net/def/crs/EPSG/0/4936

|3D geodetic in ETRS89 on GRS80
|ETRS89-GRS80h
|http://www.opengis.net/def/crs/EPSG/0/4937

|2D geodetic in ETRS89 on GRS80
|ETRS89-GRS80
|http://www.opengis.net/def/crs/EPSG/0/4258

|2D LAEA projection in ETRS89 on GRS80
|ETRS89-LAEA
|http://www.opengis.net/def/crs/EPSG/0/3035

|2D LCC projection in ETRS89 on GRS80
|ETRS89-LCC
|http://www.opengis.net/def/crs/EPSG/0/3034

|2D TM projection in ETRS89 on GRS80, zone 26N (30°W to 24°W)
|ETRS89-TM26N
|http://www.opengis.net/def/crs/EPSG/0/3038

|2D TM projection in ETRS89 on GRS80, zone 27N (24°W to 18°W)
|ETRS89-TM27N
|http://www.opengis.net/def/crs/EPSG/0/3039

|2D TM projection in ETRS89 on GRS80, zone 28N (18°W to 12°W)
|ETRS89-TM28N
|http://www.opengis.net/def/crs/EPSG/0/3040

|2D TM projection in ETRS89 on GRS80, zone 29N (12°W to 6°W)
|ETRS89-TM29N
|http://www.opengis.net/def/crs/EPSG/0/3041

|2D TM projection in ETRS89 on GRS80, zone 30N (6°W to 0°)
|ETRS89-TM30N
|http://www.opengis.net/def/crs/EPSG/0/3042

|2D TM projection in ETRS89 on GRS80, zone 31N (0° to 6°E)
|ETRS89-TM31N
|http://www.opengis.net/def/crs/EPSG/0/3043

|2D TM projection in ETRS89 on GRS80, zone 32N (6°E to 12°E)
|ETRS89-TM32N
|http://www.opengis.net/def/crs/EPSG/0/3044

|2D TM projection in ETRS89 on GRS80, zone 33N (12°E to 18°E)
|ETRS89-TM33N
|http://www.opengis.net/def/crs/EPSG/0/3045

|2D TM projection in ETRS89 on GRS80, zone 34N (18°E to 24°E)
|ETRS89-TM34N
|http://www.opengis.net/def/crs/EPSG/0/3046

|2D TM projection in ETRS89 on GRS80, zone 35N (24°E to 30°E)
|ETRS89-TM35N
|http://www.opengis.net/def/crs/EPSG/0/3047

|2D TM projection in ETRS89 on GRS80, zone 36N (30°E to 36°E)
|ETRS89-TM36N
|http://www.opengis.net/def/crs/EPSG/0/3048

|2D TM projection in ETRS89 on GRS80, zone 37N (36°E to 42°E)
|ETRS89-TM37N
|http://www.opengis.net/def/crs/EPSG/0/3049

|2D TM projection in ETRS89 on GRS80, zone 38N (42°E to 48°E)
|ETRS89-TM38N
|http://www.opengis.net/def/crs/EPSG/0/3050

|2D TM projection in ETRS89 on GRS80, zone 39N (48°E to 54°E)
|ETRS89-TM39N
|http://www.opengis.net/def/crs/EPSG/0/3051

|Height in EVRS
|EVRS
|http://www.opengis.net/def/crs/EPSG/0/5730

|3D compound: 2D geodetic in ETRS89 on GRS80, and EVRS height
|ETRS89-GRS80-EVRS
|http://www.opengis.net/def/crs/EPSG/0/7409

|===

=== Temporal reference systems

[REQUIREMENT, id="IR Requirement"]
======
_Article 11_ +
*Temporal Reference Systems*

. The default temporal reference system referred to in point 5 of part B of the Annex to Commission Regulation (EC) No 1205/2008.footnote:[OJ L 326, 4.12.2008, p. 12.] shall be used, unless other temporal reference systems are specified for a specific spatial data theme in Annex II.
======

[NOTE]
Point 5 of part B of the Annex to Commission Regulation (EC) No 1205/2008 (the INSPIRE Metadata IRs) states that the default reference system shall be the Gregorian calendar, with dates expressed in accordance with ISO 8601.

[NOTE]
ISO 8601 Data elements and interchange formats – Information interchange – Representation of dates and times is an international standard covering the exchange of date and time-related data. The purpose of this standard is to provide an unambiguous and well-defined method of representing dates and times, so as to avoid misinterpretation of numeric representations of dates and times, particularly when data is transferred between countries with different conventions for writing numeric dates and times. The standard organizes the data so the largest temporal term (the year) appears first in the data string and progresses to the smallest term (the second). It also provides for a standardized method of communicating time-based information across time zones by attaching an offset to Coordinated Universal Time (UTC).

.Some date and date/time values
====
1997:: the year 1997
1997-07-16:: 16th July 1997
1997-07-16T19:20:30+01:00:: 16th July 1997, 19h 20’ 30’’, time zone: UTC+1
====

=== Units of measure

[REQUIREMENT, id="IR Requirement"]
======
_Article 12_ +
*Other Requirements & Rules*

(…)

[start=2]
.	All measurement values shall be expressed using SI units or non-SI units accepted for use with the International System of Units, unless specified otherwise for a specific spatial data theme or type.
======
