# tag::tg-au-dataContentAndStructure[]


# end::tg-au-dataContentAndStructure[]
# tag::tg-au-applicationSchemasOverview[]
= Data content and Structure

== Application schemas - Overview

=== Application schemas included in the IRs


# end::tg-au-applicationSchemasOverview[]
# tag::tg-au-typesToBeUsed[]
The types to be used for the exchange and classification of spatial objects from data sets related to the spatial data theme {theme} are defined in the following application schemas:

* AdministrativeUnits application schema (see section {sectionApplicationSchemaAU}).
* MaritimeUnits application schema (see section {sectionApplicationSchemaMU}).


# end::tg-au-typesToBeUsed[]
# tag::tg-au-basicNotions[]
== Basic notions

# end::tg-au-basicNotions[]
# tag::tg-au-consistencyBetweenSpatialDataSets[]
=== Consistency between spatial data sets
{theme} and maritime zones will very likely be used in conjunction with data coming from other INSPIRE themes (e.g. cadastral parcels, orthoimagery, statistical units, sea regions). {theme} and maritime zones should be considered as reference data, and geometric consistency with other themes may be achieved if these other themes use {theme} or maritime zones as background data during the production or the validation of their own data.

Currently, there are no consistency rules other than those defined within the application schemas. No consistency rules between {theme} / maritime zones and other spatial data sets have been identified.


# end::tg-au-consistencyBetweenSpatialDataSets[]
# tag::tg-au-identifierManagement[]
Each spatial object type in the application schemas of the {theme} theme has the mandatory _inspireId_ attribute. Therefore each spatial object needs to provide a unique identifier. This identifier shall be maintained by the national or regional authority. The identifier consists of two parts: the namespace and a local id. The namespace uniquely identifies a national registry wherein the identifier is registered, whereas the local id uniquely identifies an object within this namespace.

Since INSPIRE objectives refer data exchange only, the maintenance and management of unique INSPIRE identifiers is out of INSPIRE scope, and is under the responsibility of the Member States.


# end::tg-au-identifierManagement[]
# tag::tg-au-temporalityRepresentation[]
=== Temporality Representation


# end::tg-au-temporalityRepresentation[]
# tag::tg-au-applicationSchemas[]
== {theme} - Application Schemas

=== Description

==== Narrative description
The {theme} data specification establishes two application schemas: AdministrativeUnits and MaritimeUnits. The dependencies between both application schemas and other schemas of the Generic Conceptual Model are illustrated in <<tg-au-classPackageStructure, Figure {counter:pic-id}>>.

The spatial object types in the AdministrativeUnits and MaritimeUnits schemas use the GeographicalName type from the Geographical Names package. The MaritimeZone spatial object type re-uses the LegalStatusValue and TechnicalStatusValue codelists from the AdministrativeUnits package and their corresponding properties.

Both packages refer to the Base Types package to use the Identifer type from the GCM.

include::../images/tg-au-images.adoc[tags=tg-au-classPackageStructure]


# end::tg-au-applicationSchemas[]
# tag::tg-au-applicationSchemaAU[]
== Application schema AdministrativeUnits

=== Description

==== Narrative Description

The application schema AdministrativeUnits provides the means for common pan-European representation of administrative division of territory in the Member States. The schema identifies three spatial object types: AdministrativeUnit, AdministrativeBoundary and Condominium.

AdministrativeUnit is the key spatial object type for representing the units of division at all levels of the administrative hierarchy. Each single unit (i.e. instance of AdministrativeUnit spatial object type) belongs to exactly one level of the respective national hierarchy.

Usually, administrative units from a higher level aggregate the units at lower level of administrative hierarchy. As this division of territory is not always strictly hierarchical and can be derived from the geometry, semantic relationships between the units of subsequent upper and lower levels were introduced.

The spatial object type AdministrativeBoundary is defined in this application schema to represent the boundaries between the neighbouring units and their boundary-specific attributes (like technical and legal status).

Usually, a single administrative unit is administered by only one administrative authority. However, in some cases a unit is co-administered by other units (authorities) and is not (directly) linked to an administrative unit at a higher level. The representation of co-administering is supported in this application schema.

In very rare cases a single administrative area is administered by two or more countries. Such an area is named condominium and supported in this application schema by the Condominium spatial object type. The correspondence between the condominium and the countries administering it are represented by a relationship between the AdministrativeUnit and Condominium spatial object types.

NOTE: Previous versions of the data specification on _Administrative Units_ contained a candidate type called NUTSRegion to accommodate requirements raised by INSPIRE stakeholders to include an explicit connection to statistical units defined by the EU-administration in the application schema AdministrativeUnits in order to link statistical information to administrative units. This candidate type was considered during the development of the data specification on Statistical Units, where it is included as an informative example of a Statistical Units data set.

In some existing implementations for administrative units data (e.g. EuroBoundaryMap), the spatial extent of administrative units is further decomposed into sub-areas, like land areas, islands, inland water or coastal water areas. The reason for this decomposition of administrative units into areas comes from the natural need for combining administrative information with other thematic information. This application schema does not differentiate between the sub-areas of administrative units because it is out of its scope. Considering the INSPIRE harmonization objectives, the correlation of administrative units with elements of other division systems can be derived from cross-theme analysis of thematic spatial objects. In the case described above, the information on decomposition of administrative units into sub-areas can be derived performing spatial analyses with data from other INSPIRE themes (e.g. Land Use theme from Annex II). See also Annex E for further information.

==== UML Overview

include::../images/tg-au-images.adoc[tags=tg-au-classAUOverview]

The AdministrativeUnit spatial object type uses the GeographicalName type from the Geographical Names package. The AdministrativeUnits package also refers the package Base Types for using the Identifer type defined in the GCM.

AdministrativeUnit is the main spatial object type included in the application schema and represents administrative units at all the levels of administrative hierarchy. Each single unit (i.e. instance of AdministrativeUnit spatial object type) belongs to exactly one hierarchy level. Information about the level in the respective national hierarchy that a certain unit belongs to is documented by the mandatory nationalLevel attribute.

The number of administrative levels differs from country to country (in the EU Member States up to 6 levels are in use, see the examples in Annex D), therefore no absolute levels can be fixed. Instead, the (spatial) correspondence between the levels is a common characteristic of national administrative hierarchies. The representation of these relationships between the units is supported in this application schema by a self-reference of the AdministrativeUnit type, and corresponding to the lowerLevelUnit and upperLevelUnit association roles. The top-down inclusion of units is expressed in the application schema by the lowerLevelUnit association role of the AdministrativeUnit spatial object type. Each unit except for those on the lowest level shall provide the relation to their lower level units. The spatial object type AdministrativeUnit is shown in detail in  <<tg-au-classAU, Figure {counter:pic-id}>>

include::../images/tg-au-images.adoc[tags=tg-au-classAU]

Similarly, the down-top relationship between the units of lower and higher levels can be determined. In fact, usually lower level units refer exactly one higher level unit. A support for describing this is provided by the upperLevelUnit association role of the AdministrativeUnit spatial object type. The only exception to this situation are the units at the highest (country) level; they have no upper level units.

In some countries the hierarchy of Administrative Units differs from the ideal strictly hierarchical organization. For instance, some units (at lowest level) are not linked to any unit at a higher level but to two or more units at same level. In order to support reporting of such situations a self-reference of AdministrativeUnit with the coAdminister and administeredBy association roles is established in this application schema.

[REQUIREMENT, id="IR Requirement"]
======
_Annex II, Section 4.4_ +
*Theme-specific Requirements*

. Each instance of spatial object type AdministrativeUnit, except for the country level unit representing a MemberState and co-administered units, shall refer exactly to one unit at a higher level of administrative hierarchy. This correspondence shall be expressed by the upperLevelUnit association role of AdministrativeUnit spatial object type.
======

[REQUIREMENT, id="IR Requirement"]
======
_Annex II, Section 4.4_ +
*Theme-specific Requirements*

[start=2]
. Each instance of spatial object type AdministrativeUnit, except for those at the lowest level, shall refer to their respective lower level units. This correspondence shall be expressed by the lowerLevelUnit association role of AdministrativeUnit spatial object type.
======

[REQUIREMENT, id="IR Requirement"]
======
_Annex II, Section 4.4_ +
*Theme-specific Requirements*

[start=3]
. If an administrative unit is co-administered by two or more other administrative units the association role administeredBy shall be used. The units co-administering this unit shall apply inverse role coAdminister.
======

The association roles involved in the three requirements above have received the voidable stereotype, which means that they only need to be provided to INSPIRE when this information is available in the source data sets.

For purposes of multilingual support in the identification of administrative units, their names are of data type GeographicalName.

For the same purpose, the names of the levels (attribute nationalLevelName) are of data type localisedCharacterString.

[PERMISSION, id="Recommendation {counter:rec-id}"]
======
The value of 'language' attribute for AdministrativeUnit.name (GeographicalName DataType) should be provided, except for the situation that the data producer does not have such information.
======

For each AdministrativeUnit a location of the authority / administration (residenceOfAuthority) can be reported. It is of data type ResidenceOfAuthority which specifies a geographical name and the position of the authority (e.g. a point geometry).

Since administrative units may consist of mainlands and exclaves, their geometric representation is expressed by the GM_MultiSurface type.

[REQUIREMENT, id="IR Requirement"]
======
_Annex II, Section 4.4_ +
*Theme-specific Requirements*

[start=4]
. Administrative units at the same level of administrative hierarchy shall not conceptually share common areas.
======

The second spatial object type in the application schema, AdministrativeBoundary, is the type representing the boundaries between neighbouring administrative units and including their boundary-specific attributes. <<tg-au-classAdministrativeBoundary, Figure {counter:pic-id}>> shows this spatial object type in detail.

include::../images/tg-au-images.adoc[tags=tg-au-classAdministrativeBoundary]

AdministrativeBoundary provides important information concerning the administrative division. In particular, it is labelled with a legal and a technical status of the boundary. The legal status refers to the political agreement between the units, whereas the technical status faces the edge-matching issues; the "edge-matched" value meaning that the boundary of neighbouring administrative units have the same set of coordinates. If available both indicators shall be provided.

The legal status is not only meant for international boundaries but also for boundaries within member states as there are also cases where the boundaries are not agreed.

This application schema defines a voidable association between AdministrativeUnit and AdministrativeBoundary spatial object types to support the expression of topological and semantic relationships that can be used in queries to avoid geometric intersections.

[REQUIREMENT, id="IR Requirement"]
======
_Annex II, Section 4.4_ +
*Theme-specific Requirements*

[start=5]
. Instances of the spatial object type AdministrativeBoundary shall correspond to the edges in the topological structure of the complete (including all levels) boundary graph.
======

[PERMISSION, id="Recommendation {counter:rec-id}"]
======
The following geometric and topological constraints are recommendations for this data specification:

[loweralpha]
. Adjacent administrative units should not overlap, i.e. their boundaries should not intersect with each other.
. There should be no gaps between adjacent administrative units.
. Unintended gaps between administrative units due to geometrical inconsistencies are in principle not allowed. Boundaries of neighboring administrative units shall have the same set of coordinates, within the specified resolution.
. The border line that limits the administrative units shall correspond to the geometries representing the boundaries of this administrative unit.
. The boundaries must not have dangles, boundaries always divide different administrative units.
======

Consistent with existing definitions, a condominium in the context of this specification is considered as a political territory over which two or more sovereign States jointly exercise their jurisdictional rights, without further territorial decomposition. Consequently, a condominium cannot be part of a national administrative hierarchy. On the other hand, condominiums might be included into national datasets and the information about them shall be shared on the European level. Condominium is shown in <<tg-au-classCondominium, Figure {counter:pic-id}>>.

include::../images/tg-au-images.adoc[tags=tg-au-classCondominium]

To support the representation of condominiums a special spatial object type is defined in the application schema AdministrativeUnits. It includes a mandatory surface geometry and an optional name. The association to the AdministrativeUnit type allows representing the connection between the condominium and the administering States.

[REQUIREMENT, id="IR Requirement"]
======
_Annex II, Section 4.4_ +
*Theme-specific Requirements*

[start=6]
. The spatial extent of a condominium may not be part of the geometry representing the spatial extent of an administrative unit.
======

[REQUIREMENT, id="IR Requirement"]
======
_Annex II, Section 4.4_ +
*Theme-specific Requirements*

[start=7]
. Condominiums can only be administered by administrative units at country level.
======

==== Identifier management

Besides the INSPIRE-identifier (inspireId attribute) each AdministrativeUnit spatial object carries an attribute with the national unit code (nationalCode attribute). This code act as a thematic identifier and it may be also unique when preceded by the CountryCode-prefix.

==== Modelling of object references

===== Internal references

Each upper level administrative unit is composed of lower level units, and each lower level unit is linked to an upper level unit, with the exceptions highlighted in section {sectionUMLOverview} are limited by boundaries.

===== External references

In most of European countries the local administrative units (communes) refer to borders of cadastral parcels. These references are not modelled in this application schema.

==== Geometry representation

In this technical specification two alternative geometric structures of boundary features are provided:

* The first structure aims to support download of mass information collected in a form of data files.
* The second structure is better suited for presenting administrative units and maritime zones using view services, as well as selective download of small portion of feature instances using direct access download services, e.g. a Web feature service.

Both structures fully comply with the AdministrativeUnits and MaritimeUnits application schemas. Users may decide to implement the structure that fits the best their individual purposes.

NOTE: The following two sections explain the mentioned structures applied to the AdministrativeUnits application schema, but they are equally valid for the MaritimeUnits application schema, except for the hierarchical relationships, which are not defined for this schema.

===== Flat model of boundary feature geometry

In this geometric model, AdministrativeBoundary feature is represented as follows:

. Each AdministrativeBoundary feature corresponds to the curve established between the two significant nodes of topological graph established with respect to the lowest level of national administrative hierarchy.
. Each single AdministrativeBoundary feature might refer one or more hierarchical levels e.g. AdministrativeBoundary features representing a part of national boundary, part of '2nd level' boundary, and part of '3rd level' boundary.
. Each AdministrativeUnit feature associates to all touching AdministrativeBoundary features.
. Each AdministrativeBoundary feature associates to all touching administrative units from all the levels of administrative hierarchy.

.Explanation of the flat model
====
Assume the following situation for the area features (instances of AdministrativeUnit):

include::../images/tg-au-images.adoc[tags=tg-au-geometryRepresentationExample1]

The polygons represent Administrative units at three levels:

. national level 1: AU1 polygon represents a country;
. national level 2: AU2 and AU3 polygons represent regions; AU2 + AU3 topologically equal to AU1
. national level 3: AU4 and AU5 represent lowest level units; AU4 + AU5 topologically equal to AU2. For AU3 there is no further subdivision.

Level 2 is topologically equivalent to level1 of administrative hierarchy. Level 3 is not topologically equivalent to levels 1 and 2.

The boundary features (BF = instances of spatial object type AdministrativeBoundary) are built based on the topological structure of the entire (including all administrative levels) boundary geometry. Each BF consist of only one curve which is built between two connected nodes in the topological network. The nationalLevel attribute of the BF contains all relevant levels of the administrative hierarchy.

In this example the following vertices are identified:

include::../images/tg-au-images.adoc[tags=tg-au-geometryRepresentationExample2]

The Points P3, P5, P7, and P8 are nodes in the topological structure, all other points are intermediate points (vertices).

Then, the curves and Boundary features are built as follows:

include::../images/tg-au-images.adoc[tags=tg-au-geometryRepresentationExample3]

* C1 = (P7, P1, P2, P3) = BF1 +
 with nationalLevel=1, 2
* C2 = (P3, P4, P5) = BF2 +
with nationalLevel=1, 2, 3
* C3 = (P5, P6, P7) = BF3 +
with nationalLevel=1, 2, 3
* C4 = (P7, P8) = BF4 +
with nationalLevel=2, 3
* C5 = (P8, P3) = BF5 +
with nationalLevel=2, 3
* C6 = (P8, P5) = BF6 +
with nationalLevel=3

Finally, the following associations between boundaries and administrative units have to be built:

|===

| *BOUNDARY -> UNIT* | *UNIT -> BOUNDARY*

| BF1 -> AU1, AU3 +
BF2 -> AU1, AU2, AU5 +
BF3 -> AU1, AU2, AU4 +
BF4 -> AU2, AU3, AU4 +
BF5 -> AU2, AU3, AU5 +
BF6 -> AU4, AU5 | AU1 -> BF1, BF2, BF3 +
AU2 -> BF2, BF3, BF4, BF5 +
AU3 -> BF1, BF4, BF5 +
AU4 -> BF3, BF4, BF6 +
AU5 -> BF2, BF5, BF6

|===
====

===== Multi-layer model of boundary features geometry

In this geometric model, AdministrativeBoundary feature is represented as follows:

. Each single AdministrativeBoundary feature represents exactly one administrative boundary established at certain level of national administrative hierarchy e.g. the boundary between Poland and Germany, the boundary between Liguria and Piemonte regions.

. The AdministrativeBoundary features (that is, boundaries between administrative units) are identified at each hierarchical level e.g.: AdministrativeBoundary features representing the national boundaries, the AdministrativeBoundary features representing '2nd level' boundaries, the AdministrativeBoundary features representing '3rd level' boundaries etc;

. The geometry of AdministrativeBoundary feature corresponds to the entire line of demarcation determined for the administrative unit at the same level as the boundary level.

. Each AdministrativeUnit feature associates only to boundaries established at the level corresponding to the level of this administrative unit.

. Each AdministrativeBoundary feature associates only to admisnitrative units that are separated by this boundary and have the same administrative level as the level of this boundary.

.Explanation of the multi-layer model
====
This example considers exactly the same situation, as discussed in the case of flat geometric model.

include::../images/tg-au-images.adoc[tags=tg-au-geometryRepresentationExample4]

The polygons represent Administrative Units at three levels:

. national level 1: AU1 polygon represents a country;
. national level 2: AU2 and AU3 polygons represent regions; AU2 + AU3 topologically equal to AU1
. national level 3: AU4 and AU5 represent lowest level units; AU4 + AU5 topologically equal to AU2

Level 2 is topologically equivalent to level1 of administrative hierarchy. Level 3 is not topologically equivalent to levels 1 and 2.

Additionally, the polygons representing the countries adjacent to AU1 have been introduced to evidence the fact that begin and end nodes of country level boundaries do not necessarily meet the begin/end node of some regional boundary. These are labeled AU-X, AU-Y, and AU-Z.

The AdministrativeBoundary features are determined independently at each level, and are based on the topological structure established separatelly for each level national administrative hierarchy. Each AdministrativeBoundary is geometrically represented by single Curve \(C), that is defined for a selected subset of nodes representing the line of demarcation between the two units.

The nationalLevel of the AdministrativeBoundary feature (BF) corresponds to the level at which this boundary was established.

In this example the following vertices are identified:

include::../images/tg-au-images.adoc[tags=tg-au-geometryRepresentationExample5]

* P10, P3 and P9 are begin/end nodes of national boundaries between AU1 and AU-X, AU1 and AU-Y, AU1 and AU-Z;
* P7 and P3 nodes are begin/end nodes of regional boundary between AU2 and AU3
* P5 and P8 nodes are begin/end nodes of lowest level boundary between AU4 and AU5

Begin and end nodes of international boundaries do not necessarily meet begin/end node of some regional boundary.

Based on the identified nodes the following boundaries at three levels of administrative structure can be determined:

include::../images/tg-au-images.adoc[tags=tg-au-geometryRepresentationExample6]

The AdministrativeBoundary features are built as follows:

*national boundaries (hierarchyLevel=1):*

* BF1.1 = C1(P9,P5,P6,P7,P1,P10)
* BF1.2 = C2(P10,P2,P3)
* BF1.3 = C3(P3,P4,P9)

include::../images/tg-au-images.adoc[tags=tg-au-geometryRepresentationExample7]

The AdministrativeBoundary features are built as follows:

*regional boundaries (hierarchyLevel=2):*

* BF2.1 = C2.1(P7,P1,P10,P2,P3)
* BF2.2 = C2.2(P3,P4,P9,P5,P6,P7)
* BF2.3 = C2.3(P7,P8,P3)

include::../images/tg-au-images.adoc[tags=tg-au-geometryRepresentationExample8]

The AdministrativeBoundary features are built as follows:

*local boundaries (hierarchyLevel=3):*

* BF3.1 = C3.1=(P5,P6,P7,P8)
* BF3.2 = C3.2(P8,P5)
* BF3.3 = C3.3(P8,P3,P4,P9,P5)

Finally, the following associations between boundaries and administrative units have to be built:

|===

| *BOUNDARY -> UNIT* | *UNIT -> BOUNDARY*

| national boundaries: +
BF1.1 -> AU1 (boundary with AU-X) +
BF1.2 -> AU1 (boundary with AU-Y) +
BF1.3 -> AU1 (boundary with AU-Z)
|
national units: +
AU1 -> BF1.1, BF1.2, BF1.3

regional boundaries: +
BF2.3 -> AU2, AU3 +
BF2.2 -> AU2 +
BF2.1 -> AU3
|
regional units: +
AU2 -> BF2.1, BF2.2 +
AU3 -> BF2.1, BF2.3

local boundaries: +
BF3.1 -> AU4 +
BF3.2 -> AU4, AU5 +
BF3.3 -> AU5
|
local units: +
AU4 -> BF3.1, BF3.2 +
AU5 -> BF3.2, BF3.3

|===
====

# end::tg-au-applicationSchemaAU[]

# tag::tg-au-featureCatalogueAU[]
=== Feature catalogue

:leveloffset: +2

include::tg-au-fc-au.adoc[]

// http://inspire-twg.jrc.ec.europa.eu/data-model/approved/r937/fc/#_P367[Click here for the Application Schema: AdministrativeUnits Feature Catalogue.]

:leveloffset: -2

# end::tg-au-featureCatalogueAU[]
# tag::tg-au-applicationSchemaMU[]
== Application schema MaritimeUnits

=== Description

==== Narrative description

The application schema MaritimeUnits provides the means for common pan-European representation of delimitation of maritime jurisdiction between coastal States. The schema identifies spatial object types for describing key sea division concepts: MaritimeBoundary, MaritimeZone (zones of different types distinguished by an attribute) and Baseline.

The MaritimeZone spatial object type represents any zone on the sea defined by international treaties and conventions, where a coastal State executes jurisdictional rights. MaritimeZone is further classified as a certain type of maritime zone by means of the zoneType attribute. The following zone types are distinguished: internal waters, territorial sea, contiguous zone, exclusive economic zone and continental shelf.

Depending on the type of zone, the jurisdictional rights of a coastal State may concern an area of seabed, ocean floor, subsoil, resources, or even the air space over the sea. Once defined, the maritime zones are used, among others, for cadastral, administrative, economic (e.g. fishery, exploring and exploiting), security or safety purposes.

Each maritime zone can belong exactly to one coastal State. At the same time a coastal State might have several maritime zones. The number of types of maritime zones established for a coastal State vary, depending on geographical and political characteristics, but each coastal State always has at least an internal waters and a territorial sea zone.

The maritime zones are directly or indirectly defined in relation to a Baseline. According to the United Nations Convention on the Law of the Sea (UNCLOS), the “baseline” is a line established by a coastal State from which the outer limits of its territorial sea and certain other outer limits are measured. In particular, the territorial sea of a coastal State is a belt of sea of a defined breadth not exceeding 12 nautical miles measured from the baselines, whereas internal waters are the waters on the landward side of the baselines of the territorial sea of the coastal State. In turn, the contiguous zone, the exclusive economic zone and the continental shelf are defined as zones beyond and adjacent to the territorial sea of a coastal State.

There can be more than one baseline determined by a State. For instance, France has two baselines: one in the north between Belgium to Spain, and the second in the south - between Spain and Italy.

include::../images/tg-au-images.adoc[tags=tg-au-conceptsMaritimeUnits]

Each zone must be delimited by MaritimeBoundary spatial objects. A MaritimeBoundary is a line that separates any type of maritime jurisdiction (i.e. fishery, petroleum and other resources of the sea as well as other uses of the sea). MaritimeBoundary may be twofold:

* it may define a seaward outer limit of certain maritime zone of a coastal State,
* it may represent a limit of the maritime zone of States with opposite or adjacent coasts.

A Maritime boundary is always subject to international treaties between the States and in a legal context it may be either agreed or in dispute. In case the maritime boundary is established between the adjacent coastal States, it shall be a natural prolongation of the administrative boundary on land.

==== UML Overview

The complete MaritimeUnits application schema is shown in <<tg-au-classMUOverview, Figure {counter:pic-id}>>  and described in detail below.

include::../images/tg-au-images.adoc[tags=tg-au-classMUOverview]

MaritimeZone is a spatial object type providing the common characteristics of all maritime zones that can be established by a coastal State on the sea. Each maritime zone is represented geometrically by the GM_MultiSurface data type and it can belong to exactly one coastal State. Information about the State executing jurisdictional rights over a certain zone is documented by the mandatory countryCode attribute.
In some specific cases a maritime zone may be known under a specific unique geographical name. In order to support the depiction of zones using geographical names a voidable attribute name, of GeographicalName data type, is also provided.

The specific type of maritime zone is classified and distinguished by means of the zoneType attribute of the MaritimeZone spatial object type. The values in the related code list (MaritimeZoneTypeValue) express the diversity of maritime zones available: internal waters (designated by the code list value _internalWaters_), territorial sea (_territorialSea_), contiguous zone (_contiguousZone_), exclusive economic zone (_exclusiveEconomicZone_) or continental shelf (_continentalShelf_).

include::../images/tg-au-images.adoc[tags=tg-au-classMaritimeZone]

[PERMISSION, id="Recommendation {counter:rec-id}"]
======
According to the UNCLOS, each coastal State is allowed to determine its territorial sea and internal waters. For this reason the representation of the territorial sea and the internal waters should always be present in a dataset providing data according to this application schema.
======

[NOTE]
The territorialSea and internalWaters values of the MaritimeZoneTypeValue code list specifically represent these concepts.

Other kinds of maritime zones may be additionally provided depending on the geographical and political situation in a sea region. For this reason no absolute number of types of zones per State may be fixed.

{counter2:pic-id}

By definition there are well known topological relationships between the various types of zones. In particular (see also <<tg-au-classMUOverview, Figure {counter:pic-id}>> and <<tg-au-recommendationMaritimeUnits, following Recommendation>>):

* the internal waters of a coastal State shall be adjacent to the AdministrativeUnit spatial object representing the State (i.e. where the attribute nationalLevel is equal to ’1stOrder’).
* the territorial sea of a coastal State and its internal waters shall be adjacent on the Baseline.
* the contiguous zone, exclusive economic zone and continental shelf shall be adjacent to the territorial sea.
* the continental shelf shall include the exclusive economic zone.
* the exclusive economic zone shall include the contiguous zone.

[[tg-au-recommendationMaritimeUnits]]
[PERMISSION, id="Recommendation {counter:rec-id}"]
======
The following geometric and topological constraints are recommendations for this data specification:

* the internal waters of a coastal State should be adjacent to the AdministrativeUnit spatial object representing the State (i.e. where the attribute nationalLevel is equal to ’1stOrder’).
* the territorial sea of a coastal State and its internal waters should be adjacent on the Baseline.
* the contiguous zone, exclusive economic zone and continental shelf should be adjacent to the territorial sea.
* the continental shelf should include the exclusive economic zone.
* the exclusive economic zone should include the contiguous zone.
======

[NOTE]
The relationships mentioned above are not explicitly expressed in the UML model for simplicity, nevertheless they should be reflected in the data.

The Baseline spatial object type is a key notion to determine maritime zones. It serves as reference to calculate the breadth of territorial sea, as well as the outer limits of contiguous zones, exclusive economic zones and continental shelves. The baseline is composed of baseline segments (see the segment association role), and each baseline segment can be established based on different baseline calculation methods (see the segmentType attribute of the BaselineSegment data type). The rules for establishing baselines are provided in Article 5 of UNCLOS.

include::../images/tg-au-images.adoc[tags=tg-au-classBaseline]

The instances of the MaritimeBoundary spatial object type represents the borders on sea between the coastal States. They may represent:
* a seaward outer limit of certain maritime zone of a coastal State.
* a limit of the maritime zone of States with opposite or adjacent coasts.

If a MaritimeBoundary spatial object represents a boundary between adjacent coastal States, its start point shall be the same as the end point of the administrative boundary on land.

Each instance of the MaritimeZone spatial object type provides the countryCode of a coastal State that executes jurisdictional right on it.

{counter2:pic-id}
{counter2:pic-id}

For purposes of multilingual support in the identification of maritime zones, their names are of data type GeographicalName.
The MaritimeBoundary spatial object type supports the representation of the boundaries established on seas between the neighbouring coastal States. <<tg-au-classMaritimeBoundary, Figure {counter:pic-id}>> shows this spatial object type in detail.

include::../images/tg-au-images.adoc[tags=tg-au-classMaritimeBoundary]

MaritimeBoundary provides important information concerning sea division. In particular, it is labelled with a legal and a technical status of the boundary. The legal status refers to the political agreement between the units, whereas the technical status faces the edge-matching issues; the “edge-matched” value meaning that the boundary of neighbouring maritime zones have the same set of coordinates. In contrast, there are also cases where the maritime boundaries are not agreed. If available both indicators shall be provided

The MaritimeUnits application schema defines a voidable association between the MaritimeZone and the MaritimeBoundary spatial object types to support the expression of topological and semantic relationships that may be used in queries to avoid geometric intersections.

==== Modelling of object references

No specific requirements or recommendations are defined for object references in the MaritimeUnits application schema.
# end::tg-au-applicationSchemaMU[]

# tag::tg-au-featureCatalogueMU[]
=== Feature catalogue

:leveloffset: +2

include::tg-au-fc-mu.adoc[]

// http://inspire.ec.europa.eu/data-model/approved/r4618/fc/#_P3467[Click here for the Application Schema: MaritimeUnits Feature Catalogue.]

:leveloffset: -2

# end::tg-au-featureCatalogueMU[]
