# tag::tg-au-title[]
= Acknowledgements
# end::tg-au-title[]

# tag::tg-au-thematicWorkingGroup[]
The Thematic Working Group Administrative Units (TWG-AU) included:
Jesper Paasch (TWG Facilitator), Geir Myrind (TWG Editor), Ulrich Düren, Alina Kmiecik, Frederic Mortier, Ingrid Naumann, Katalin Tóth (European Commission contact point).

The initial MaritimeUnits application schema has been developed by the Annex III TWG Oceanographic geographical features & Sea Regions (TWG-OF-SR), which included:
Keiran Millard (TWG Facilitator), Dominic Lowe (TWG Editor), Hans Mose Jensen, Marc Roesbeke, Carlo Brandini, Nuria Hermida, Maria Olvido Tello, Alessandro Sarretta (European Commission contact point till May 2012), Tomáš Řezník (European Commission contact point from May till August 2012), Michael Lutz & Vlado Cetl (European Commission contact points from August 2012).

The combined data specification including both application schemas has been created by Alina Kmiecik.
# tag::tg-au-thematicWorkingGroup[]